### ISSUE TITLE
User update

### ISSUE THREAD

**Issue by gpasztor87** [RFT-LEV-KondiBazis-WEB/KondiBazis-Backend#5]
Jelenleg nem jön vissza rendesen a hibaüzenet, ha helytelen adatokat küldök fel.

Továbbá ha az email címemet nem akarom megváltoztatni, akkor sem menti el az adatokat, mert azt írja, hogy már létezik az email cím. Valahogy másképp kellene ezt vizsgálni. 

Ja és van egy elírás a sikeres válaszban :)

**Comment by bakbalazs** [comment]
Javítva
