### ISSUE TITLE
Hiányzó show metódus

### ISSUE THREAD

**Issue by gpasztor87** [RFT-LEV-KondiBazis-WEB/KondiBazis-Backend#6]
Hiányzik minden Rest controllernél a show metódus.
Erre akkor van szükség, amikor meg akarom nyitni az update oldalt.

A show metódus get requestet szokott fogadni, és így szokott kinézni:
GET /{resource}/id.

Ebben az esetben adja vissza a kért objektumot a megszokott módon: {data: {...}}

**Comment by ludmanl** [comment]
Kész. Átraktam taigára is.
